window.DEMO_DATA = 
{
  "generatedAt": "2026-02-27T07:59:59Z",
  "tableImpact": [
    {
      "table": "Orders",
      "script_count": 50
    },
    {
      "table": "Products",
      "script_count": 36
    },
    {
      "table": "OrderItems",
      "script_count": 31
    },
    {
      "table": "Stores",
      "script_count": 29
    },
    {
      "table": "Categories",
      "script_count": 26
    },
    {
      "table": "Customers",
      "script_count": 14
    },
    {
      "table": "PageViews",
      "script_count": 13
    },
    {
      "table": "Payments",
      "script_count": 7
    },
    {
      "table": "InventoryMovements",
      "script_count": 6
    },
    {
      "table": "Promotions",
      "script_count": 1
    }
  ],
  "scripts": [
    {
      "script_id": 1,
      "script_file": "0001_daily_revenue_with_7_day_moving_average_last_30_days.sql",
      "title": "Daily revenue with 7-day moving average (last 30 days)",
      "category": "report",
      "complexity": 6,
      "needs_manual_review": false,
      "tags": "SELECT|CTE|WINDOW|DATEADD",
      "tables": "Orders",
      "executions": 7,
      "total_duration_ms": 5088,
      "avg_duration_ms": 726.86,
      "total_cpu_ms": 4270,
      "total_reads": 81444,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 29,
      "final_total_tokens": 6443,
      "final_warnings": null
    },
    {
      "script_id": 2,
      "script_file": "0002_ingest_order_items_from_json_payload_openjson.sql",
      "title": "Ingest order items from JSON payload (OPENJSON)",
      "category": "etl",
      "complexity": 9,
      "needs_manual_review": true,
      "tags": "OPENJSON|JSON|ETL",
      "tables": "OrderItems",
      "executions": 13,
      "total_duration_ms": 32529,
      "avg_duration_ms": 2502.23,
      "total_cpu_ms": 19591,
      "total_reads": 616222,
      "conversion_attempts": 2,
      "final_status": "failed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 33,
      "final_total_tokens": 5351,
      "final_warnings": "OPENJSON -> JSON_TABLE (MySQL 8). Confirm JSON types and precision."
    },
    {
      "script_id": 3,
      "script_file": "0003_quick_look_products_rows.sql",
      "title": "Quick look: Products rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Products",
      "executions": 7,
      "total_duration_ms": 91,
      "avg_duration_ms": 13.0,
      "total_cpu_ms": 59,
      "total_reads": 1402,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 17,
      "final_total_tokens": 6422,
      "final_warnings": null
    },
    {
      "script_id": 4,
      "script_file": "0004_quick_look_customers_rows.sql",
      "title": "Quick look: Customers rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Customers",
      "executions": 14,
      "total_duration_ms": 180,
      "avg_duration_ms": 12.86,
      "total_cpu_ms": 115,
      "total_reads": 3254,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 7,
      "final_total_tokens": 5523,
      "final_warnings": null
    },
    {
      "script_id": 5,
      "script_file": "0005_store_sales_by_category_last_7_days.sql",
      "title": "Store sales by category (last 7 days)",
      "category": "report",
      "complexity": 6,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 57,
      "total_duration_ms": 35673,
      "avg_duration_ms": 625.84,
      "total_cpu_ms": 23480,
      "total_reads": 631862,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 16,
      "final_total_tokens": 4555,
      "final_warnings": null
    },
    {
      "script_id": 6,
      "script_file": "0006_revenue_by_day_formatted.sql",
      "title": "Revenue by day (formatted)",
      "category": "report",
      "complexity": 5,
      "needs_manual_review": true,
      "tags": "FORMAT|datetime|reporting",
      "tables": "Orders",
      "executions": 20,
      "total_duration_ms": 10608,
      "avg_duration_ms": 530.4,
      "total_cpu_ms": 7260,
      "total_reads": 181609,
      "conversion_attempts": 2,
      "final_status": "passed_with_notes",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 16,
      "final_total_tokens": 6731,
      "final_warnings": "T-SQL FORMAT is expensive; DATE_FORMAT in MySQL. Prefer grouping by DATE(OrderDate) if possible."
    },
    {
      "script_id": 7,
      "script_file": "0007_store_sales_by_category_last_30_days.sql",
      "title": "Store sales by category (last 30 days)",
      "category": "report",
      "complexity": 6,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 36,
      "total_duration_ms": 30375,
      "avg_duration_ms": 843.75,
      "total_cpu_ms": 21096,
      "total_reads": 478969,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 25,
      "final_total_tokens": 4118,
      "final_warnings": null
    },
    {
      "script_id": 8,
      "script_file": "0008_quick_look_orders_rows.sql",
      "title": "Quick look: Orders rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD|IN",
      "tables": "Orders",
      "executions": 8,
      "total_duration_ms": 351,
      "avg_duration_ms": 43.88,
      "total_cpu_ms": 243,
      "total_reads": 6778,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 8,
      "final_total_tokens": 4181,
      "final_warnings": null
    },
    {
      "script_id": 9,
      "script_file": "0009_daily_revenue_with_7_day_moving_average_last_30_days.sql",
      "title": "Daily revenue with 7-day moving average (last 30 days)",
      "category": "report",
      "complexity": 7,
      "needs_manual_review": false,
      "tags": "SELECT|CTE|WINDOW|DATEADD",
      "tables": "Orders",
      "executions": 9,
      "total_duration_ms": 9468,
      "avg_duration_ms": 1052.0,
      "total_cpu_ms": 5802,
      "total_reads": 136698,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 29,
      "final_total_tokens": 3674,
      "final_warnings": null
    },
    {
      "script_id": 10,
      "script_file": "0010_monthly_revenue_pivot_by_store.sql",
      "title": "Monthly revenue pivot by store",
      "category": "report",
      "complexity": 8,
      "needs_manual_review": true,
      "tags": "PIVOT|reporting",
      "tables": "Orders|Stores",
      "executions": 66,
      "total_duration_ms": 84246,
      "avg_duration_ms": 1276.45,
      "total_cpu_ms": 57576,
      "total_reads": 1376767,
      "conversion_attempts": 3,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 24,
      "final_total_tokens": 5322,
      "final_warnings": "PIVOT rewritten as conditional aggregation; verify performance & indexes."
    },
    {
      "script_id": 11,
      "script_file": "0011_store_sales_by_category_last_60_days.sql",
      "title": "Store sales by category (last 60 days)",
      "category": "report",
      "complexity": 4,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 64,
      "total_duration_ms": 21792,
      "avg_duration_ms": 340.5,
      "total_cpu_ms": 15988,
      "total_reads": 380432,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 23,
      "final_total_tokens": 4392,
      "final_warnings": null
    },
    {
      "script_id": 12,
      "script_file": "0012_store_sales_by_category_last_180_days.sql",
      "title": "Store sales by category (last 180 days)",
      "category": "report",
      "complexity": 6,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 16,
      "total_duration_ms": 11815,
      "avg_duration_ms": 738.44,
      "total_cpu_ms": 8370,
      "total_reads": 175705,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 20,
      "final_total_tokens": 6786,
      "final_warnings": null
    },
    {
      "script_id": 13,
      "script_file": "0013_quick_look_inventorymovements_rows.sql",
      "title": "Quick look: InventoryMovements rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "InventoryMovements",
      "executions": 334,
      "total_duration_ms": 4188,
      "avg_duration_ms": 12.54,
      "total_cpu_ms": 2657,
      "total_reads": 69348,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 10,
      "final_total_tokens": 5203,
      "final_warnings": null
    },
    {
      "script_id": 14,
      "script_file": "0014_quick_look_customers_rows.sql",
      "title": "Quick look: Customers rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "Customers",
      "executions": 24,
      "total_duration_ms": 3084,
      "avg_duration_ms": 128.5,
      "total_cpu_ms": 2091,
      "total_reads": 48489,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 21,
      "final_total_tokens": 5138,
      "final_warnings": null
    },
    {
      "script_id": 15,
      "script_file": "0015_ad_hoc_troubleshooting_query_nolock.sql",
      "title": "Ad-hoc troubleshooting query (NOLOCK)",
      "category": "query",
      "complexity": 6,
      "needs_manual_review": true,
      "tags": "NOLOCK|performance|TOP",
      "tables": "Orders",
      "executions": 151,
      "total_duration_ms": 72843,
      "avg_duration_ms": 482.4,
      "total_cpu_ms": 49640,
      "total_reads": 1218610,
      "conversion_attempts": 2,
      "final_status": "passed_with_notes",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 24,
      "final_total_tokens": 4788,
      "final_warnings": "Removed NOLOCK hint; consider transaction isolation needs"
    },
    {
      "script_id": 16,
      "script_file": "0016_sessionize_page_views_into_visits_temp_table.sql",
      "title": "Sessionize page views into visits (#temp table)",
      "category": "analytics",
      "complexity": 7,
      "needs_manual_review": true,
      "tags": "TEMP|analytics|WINDOW",
      "tables": "PageViews",
      "executions": 56,
      "total_duration_ms": 53992,
      "avg_duration_ms": 964.14,
      "total_cpu_ms": 36916,
      "total_reads": 851817,
      "conversion_attempts": 3,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 29,
      "final_total_tokens": 5676,
      "final_warnings": "#temp converted to TEMPORARY TABLE. Ensure MySQL 8 window functions are enabled."
    },
    {
      "script_id": 17,
      "script_file": "0017_quick_look_inventorymovements_rows.sql",
      "title": "Quick look: InventoryMovements rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "InventoryMovements",
      "executions": 18,
      "total_duration_ms": 767,
      "avg_duration_ms": 42.61,
      "total_cpu_ms": 480,
      "total_reads": 11891,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 14,
      "final_total_tokens": 4184,
      "final_warnings": null
    },
    {
      "script_id": 18,
      "script_file": "0018_quick_look_pageviews_rows.sql",
      "title": "Quick look: PageViews rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "PageViews",
      "executions": 20,
      "total_duration_ms": 950,
      "avg_duration_ms": 47.5,
      "total_cpu_ms": 608,
      "total_reads": 14632,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 12,
      "final_total_tokens": 3492,
      "final_warnings": null
    },
    {
      "script_id": 19,
      "script_file": "0019_store_sales_by_category_last_7_days.sql",
      "title": "Store sales by category (last 7 days)",
      "category": "report",
      "complexity": 6,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 122,
      "total_duration_ms": 83840,
      "avg_duration_ms": 687.21,
      "total_cpu_ms": 57562,
      "total_reads": 1341444,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 13,
      "final_total_tokens": 4571,
      "final_warnings": null
    },
    {
      "script_id": 20,
      "script_file": "0020_store_sales_by_category_last_14_days.sql",
      "title": "Store sales by category (last 14 days)",
      "category": "report",
      "complexity": 6,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 10,
      "total_duration_ms": 6161,
      "avg_duration_ms": 616.1,
      "total_cpu_ms": 3986,
      "total_reads": 115244,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 15,
      "final_total_tokens": 6500,
      "final_warnings": null
    },
    {
      "script_id": 21,
      "script_file": "0021_store_sales_by_category_last_180_days.sql",
      "title": "Store sales by category (last 180 days)",
      "category": "report",
      "complexity": 7,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 19,
      "total_duration_ms": 20359,
      "avg_duration_ms": 1071.53,
      "total_cpu_ms": 13286,
      "total_reads": 354402,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 26,
      "final_total_tokens": 5661,
      "final_warnings": null
    },
    {
      "script_id": 22,
      "script_file": "0022_quick_look_orders_rows.sql",
      "title": "Quick look: Orders rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD|IN",
      "tables": "Orders",
      "executions": 19,
      "total_duration_ms": 2274,
      "avg_duration_ms": 119.68,
      "total_cpu_ms": 1595,
      "total_reads": 36008,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 30,
      "final_total_tokens": 4959,
      "final_warnings": null
    },
    {
      "script_id": 23,
      "script_file": "0023_store_sales_by_category_last_14_days.sql",
      "title": "Store sales by category (last 14 days)",
      "category": "report",
      "complexity": 6,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 39,
      "total_duration_ms": 24668,
      "avg_duration_ms": 632.51,
      "total_cpu_ms": 17101,
      "total_reads": 401050,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 21,
      "final_total_tokens": 6439,
      "final_warnings": null
    },
    {
      "script_id": 24,
      "script_file": "0024_store_sales_by_category_last_7_days.sql",
      "title": "Store sales by category (last 7 days)",
      "category": "report",
      "complexity": 7,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 23,
      "total_duration_ms": 18033,
      "avg_duration_ms": 784.04,
      "total_cpu_ms": 11912,
      "total_reads": 325491,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 18,
      "final_total_tokens": 6004,
      "final_warnings": null
    },
    {
      "script_id": 25,
      "script_file": "0025_quick_look_products_rows.sql",
      "title": "Quick look: Products rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Products",
      "executions": 16,
      "total_duration_ms": 708,
      "avg_duration_ms": 44.25,
      "total_cpu_ms": 465,
      "total_reads": 12578,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 14,
      "final_total_tokens": 4180,
      "final_warnings": null
    },
    {
      "script_id": 26,
      "script_file": "0026_daily_revenue_with_7_day_moving_average_last_90_days.sql",
      "title": "Daily revenue with 7-day moving average (last 90 days)",
      "category": "report",
      "complexity": 7,
      "needs_manual_review": false,
      "tags": "SELECT|CTE|WINDOW|DATEADD",
      "tables": "Orders",
      "executions": 7,
      "total_duration_ms": 7486,
      "avg_duration_ms": 1069.43,
      "total_cpu_ms": 4351,
      "total_reads": 129974,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 38,
      "final_total_tokens": 6935,
      "final_warnings": null
    },
    {
      "script_id": 27,
      "script_file": "0027_store_sales_by_category_last_180_days.sql",
      "title": "Store sales by category (last 180 days)",
      "category": "report",
      "complexity": 4,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 6,
      "total_duration_ms": 1556,
      "avg_duration_ms": 259.33,
      "total_cpu_ms": 1168,
      "total_reads": 31079,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 23,
      "final_total_tokens": 3676,
      "final_warnings": null
    },
    {
      "script_id": 28,
      "script_file": "0028_quick_look_pageviews_rows.sql",
      "title": "Quick look: PageViews rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "PageViews",
      "executions": 6,
      "total_duration_ms": 378,
      "avg_duration_ms": 63.0,
      "total_cpu_ms": 246,
      "total_reads": 5972,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 11,
      "final_total_tokens": 3269,
      "final_warnings": null
    },
    {
      "script_id": 29,
      "script_file": "0029_quick_look_pageviews_rows.sql",
      "title": "Quick look: PageViews rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "PageViews",
      "executions": 5,
      "total_duration_ms": 54,
      "avg_duration_ms": 10.8,
      "total_cpu_ms": 35,
      "total_reads": 1019,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 10,
      "final_total_tokens": 5627,
      "final_warnings": null
    },
    {
      "script_id": 30,
      "script_file": "0030_quick_look_products_rows.sql",
      "title": "Quick look: Products rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Products",
      "executions": 14,
      "total_duration_ms": 157,
      "avg_duration_ms": 11.21,
      "total_cpu_ms": 91,
      "total_reads": 2946,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 13,
      "final_total_tokens": 3477,
      "final_warnings": null
    },
    {
      "script_id": 31,
      "script_file": "0031_quick_look_orders_rows.sql",
      "title": "Quick look: Orders rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD|IN",
      "tables": "Orders",
      "executions": 32,
      "total_duration_ms": 3520,
      "avg_duration_ms": 110.0,
      "total_cpu_ms": 2309,
      "total_reads": 56486,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 14,
      "final_total_tokens": 6380,
      "final_warnings": null
    },
    {
      "script_id": 32,
      "script_file": "0032_store_sales_by_category_last_90_days.sql",
      "title": "Store sales by category (last 90 days)",
      "category": "report",
      "complexity": 4,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 44,
      "total_duration_ms": 11947,
      "avg_duration_ms": 271.52,
      "total_cpu_ms": 8020,
      "total_reads": 207323,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 8,
      "final_total_tokens": 5472,
      "final_warnings": null
    },
    {
      "script_id": 33,
      "script_file": "0033_quick_look_pageviews_rows.sql",
      "title": "Quick look: PageViews rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "PageViews",
      "executions": 1059,
      "total_duration_ms": 124617,
      "avg_duration_ms": 117.67,
      "total_cpu_ms": 83644,
      "total_reads": 2041377,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 24,
      "final_total_tokens": 5752,
      "final_warnings": null
    },
    {
      "script_id": 34,
      "script_file": "0034_quick_look_payments_rows.sql",
      "title": "Quick look: Payments rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Payments",
      "executions": 114,
      "total_duration_ms": 1477,
      "avg_duration_ms": 12.96,
      "total_cpu_ms": 946,
      "total_reads": 24220,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 14,
      "final_total_tokens": 3900,
      "final_warnings": null
    },
    {
      "script_id": 35,
      "script_file": "0035_quick_look_customers_rows.sql",
      "title": "Quick look: Customers rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Customers",
      "executions": 9,
      "total_duration_ms": 132,
      "avg_duration_ms": 14.67,
      "total_cpu_ms": 85,
      "total_reads": 2618,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 19,
      "final_total_tokens": 3002,
      "final_warnings": null
    },
    {
      "script_id": 36,
      "script_file": "0036_quick_look_customers_rows.sql",
      "title": "Quick look: Customers rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "Customers",
      "executions": 30,
      "total_duration_ms": 3594,
      "avg_duration_ms": 119.8,
      "total_cpu_ms": 2430,
      "total_reads": 58463,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 26,
      "final_total_tokens": 3081,
      "final_warnings": null
    },
    {
      "script_id": 37,
      "script_file": "0037_store_sales_by_category_last_14_days.sql",
      "title": "Store sales by category (last 14 days)",
      "category": "report",
      "complexity": 7,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 14,
      "total_duration_ms": 11521,
      "avg_duration_ms": 822.93,
      "total_cpu_ms": 8440,
      "total_reads": 184846,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 20,
      "final_total_tokens": 6351,
      "final_warnings": null
    },
    {
      "script_id": 38,
      "script_file": "0038_dynamic_sql_ad_hoc_filter_builder_sp_executesql.sql",
      "title": "Dynamic SQL: ad-hoc filter builder (sp_executesql)",
      "category": "query",
      "complexity": 10,
      "needs_manual_review": true,
      "tags": "dynamic_sql|sp_executesql",
      "tables": "Orders",
      "executions": 8,
      "total_duration_ms": 9910,
      "avg_duration_ms": 1238.75,
      "total_cpu_ms": 5951,
      "total_reads": 144134,
      "conversion_attempts": 3,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 46,
      "final_total_tokens": 6767,
      "final_warnings": "sp_executesql -> PREPARE/EXECUTE; beware SQL injection; parameterization differs."
    },
    {
      "script_id": 39,
      "script_file": "0039_store_sales_by_category_last_7_days.sql",
      "title": "Store sales by category (last 7 days)",
      "category": "report",
      "complexity": 5,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 8,
      "total_duration_ms": 4024,
      "avg_duration_ms": 503.0,
      "total_cpu_ms": 2601,
      "total_reads": 69006,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 28,
      "final_total_tokens": 5277,
      "final_warnings": null
    },
    {
      "script_id": 40,
      "script_file": "0040_sessionize_page_views_into_visits_temp_table.sql",
      "title": "Sessionize page views into visits (#temp table)",
      "category": "analytics",
      "complexity": 7,
      "needs_manual_review": true,
      "tags": "TEMP|analytics|WINDOW",
      "tables": "PageViews",
      "executions": 15,
      "total_duration_ms": 16629,
      "avg_duration_ms": 1108.6,
      "total_cpu_ms": 10637,
      "total_reads": 260345,
      "conversion_attempts": 2,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 18,
      "final_total_tokens": 4262,
      "final_warnings": "#temp converted to TEMPORARY TABLE. Ensure MySQL 8 window functions are enabled."
    },
    {
      "script_id": 41,
      "script_file": "0041_store_sales_by_category_last_60_days.sql",
      "title": "Store sales by category (last 60 days)",
      "category": "report",
      "complexity": 6,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 84,
      "total_duration_ms": 62849,
      "avg_duration_ms": 748.2,
      "total_cpu_ms": 43292,
      "total_reads": 1019295,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 15,
      "final_total_tokens": 3527,
      "final_warnings": null
    },
    {
      "script_id": 42,
      "script_file": "0042_store_sales_by_category_last_180_days.sql",
      "title": "Store sales by category (last 180 days)",
      "category": "report",
      "complexity": 4,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 14,
      "total_duration_ms": 3656,
      "avg_duration_ms": 261.14,
      "total_cpu_ms": 2504,
      "total_reads": 69889,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 12,
      "final_total_tokens": 5527,
      "final_warnings": null
    },
    {
      "script_id": 43,
      "script_file": "0043_sessionize_page_views_into_visits_temp_table.sql",
      "title": "Sessionize page views into visits (#temp table)",
      "category": "analytics",
      "complexity": 7,
      "needs_manual_review": true,
      "tags": "TEMP|analytics|WINDOW",
      "tables": "PageViews",
      "executions": 6,
      "total_duration_ms": 6171,
      "avg_duration_ms": 1028.5,
      "total_cpu_ms": 4278,
      "total_reads": 85404,
      "conversion_attempts": 2,
      "final_status": "passed_with_notes",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 36,
      "final_total_tokens": 6514,
      "final_warnings": "#temp converted to TEMPORARY TABLE. Ensure MySQL 8 window functions are enabled."
    },
    {
      "script_id": 44,
      "script_file": "0044_quick_look_customers_rows.sql",
      "title": "Quick look: Customers rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Customers",
      "executions": 9,
      "total_duration_ms": 454,
      "avg_duration_ms": 50.44,
      "total_cpu_ms": 308,
      "total_reads": 6665,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 17,
      "final_total_tokens": 6117,
      "final_warnings": null
    },
    {
      "script_id": 45,
      "script_file": "0045_quick_look_orders_rows.sql",
      "title": "Quick look: Orders rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD|IN",
      "tables": "Orders",
      "executions": 89,
      "total_duration_ms": 1195,
      "avg_duration_ms": 13.43,
      "total_cpu_ms": 814,
      "total_reads": 19351,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 12,
      "final_total_tokens": 5317,
      "final_warnings": null
    },
    {
      "script_id": 46,
      "script_file": "0046_filter_customers_by_comma_separated_status_list_cross_apply.sql",
      "title": "Filter customers by comma-separated status list (CROSS APPLY + STRING_SPLIT)",
      "category": "query",
      "complexity": 9,
      "needs_manual_review": true,
      "tags": "CROSS APPLY|STRING_SPLIT|reporting",
      "tables": "Customers",
      "executions": 13,
      "total_duration_ms": 10184,
      "avg_duration_ms": 783.38,
      "total_cpu_ms": 7506,
      "total_reads": 173022,
      "conversion_attempts": 3,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 16,
      "final_total_tokens": 4295,
      "final_warnings": "CROSS APPLY/STRING_SPLIT rewritten using FIND_IN_SET; consider normalization for scale."
    },
    {
      "script_id": 47,
      "script_file": "0047_backfill_orderitems_linetotal_and_orders_total.sql",
      "title": "Backfill OrderItems.LineTotal and Orders.Total",
      "category": "maintenance",
      "complexity": 5,
      "needs_manual_review": true,
      "tags": "DML|maintenance|TRANSACTION",
      "tables": "OrderItems|Orders",
      "executions": 24,
      "total_duration_ms": 17122,
      "avg_duration_ms": 713.42,
      "total_cpu_ms": 11839,
      "total_reads": 318376,
      "conversion_attempts": 2,
      "final_status": "passed_with_notes",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 15,
      "final_total_tokens": 6063,
      "final_warnings": "UPDATE ... FROM rewritten using JOIN; validate totals and rounding behavior."
    },
    {
      "script_id": 48,
      "script_file": "0048_quick_look_payments_rows.sql",
      "title": "Quick look: Payments rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Payments",
      "executions": 551,
      "total_duration_ms": 29544,
      "avg_duration_ms": 53.62,
      "total_cpu_ms": 19438,
      "total_reads": 493924,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 9,
      "final_total_tokens": 2600,
      "final_warnings": null
    },
    {
      "script_id": 49,
      "script_file": "0049_quick_look_payments_rows.sql",
      "title": "Quick look: Payments rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Payments",
      "executions": 14,
      "total_duration_ms": 610,
      "avg_duration_ms": 43.57,
      "total_cpu_ms": 402,
      "total_reads": 11056,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 15,
      "final_total_tokens": 5908,
      "final_warnings": null
    },
    {
      "script_id": 50,
      "script_file": "0050_quick_look_customers_rows.sql",
      "title": "Quick look: Customers rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "Customers",
      "executions": 11,
      "total_duration_ms": 1562,
      "avg_duration_ms": 142.0,
      "total_cpu_ms": 1028,
      "total_reads": 27833,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 28,
      "final_total_tokens": 5310,
      "final_warnings": null
    },
    {
      "script_id": 51,
      "script_file": "0051_store_sales_by_category_last_7_days.sql",
      "title": "Store sales by category (last 7 days)",
      "category": "report",
      "complexity": 5,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 25,
      "total_duration_ms": 10604,
      "avg_duration_ms": 424.16,
      "total_cpu_ms": 7713,
      "total_reads": 188653,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 13,
      "final_total_tokens": 3863,
      "final_warnings": null
    },
    {
      "script_id": 52,
      "script_file": "0052_quick_look_products_rows.sql",
      "title": "Quick look: Products rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Products",
      "executions": 16,
      "total_duration_ms": 222,
      "avg_duration_ms": 13.88,
      "total_cpu_ms": 137,
      "total_reads": 3939,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 9,
      "final_total_tokens": 4696,
      "final_warnings": null
    },
    {
      "script_id": 53,
      "script_file": "0053_store_sales_by_category_last_90_days.sql",
      "title": "Store sales by category (last 90 days)",
      "category": "report",
      "complexity": 5,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 7,
      "total_duration_ms": 4526,
      "avg_duration_ms": 646.57,
      "total_cpu_ms": 3125,
      "total_reads": 75379,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 23,
      "final_total_tokens": 4557,
      "final_warnings": null
    },
    {
      "script_id": 54,
      "script_file": "0054_quick_look_inventorymovements_rows.sql",
      "title": "Quick look: InventoryMovements rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "InventoryMovements",
      "executions": 9,
      "total_duration_ms": 577,
      "avg_duration_ms": 64.11,
      "total_cpu_ms": 370,
      "total_reads": 9584,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 20,
      "final_total_tokens": 5849,
      "final_warnings": null
    },
    {
      "script_id": 55,
      "script_file": "0055_quick_look_pageviews_rows.sql",
      "title": "Quick look: PageViews rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "PageViews",
      "executions": 80,
      "total_duration_ms": 4190,
      "avg_duration_ms": 52.38,
      "total_cpu_ms": 2753,
      "total_reads": 69343,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 22,
      "final_total_tokens": 6048,
      "final_warnings": null
    },
    {
      "script_id": 56,
      "script_file": "0056_filter_customers_by_comma_separated_status_list_cross_apply.sql",
      "title": "Filter customers by comma-separated status list (CROSS APPLY + STRING_SPLIT)",
      "category": "query",
      "complexity": 9,
      "needs_manual_review": true,
      "tags": "CROSS APPLY|STRING_SPLIT|reporting",
      "tables": "Customers",
      "executions": 13,
      "total_duration_ms": 14030,
      "avg_duration_ms": 1079.23,
      "total_cpu_ms": 9083,
      "total_reads": 235187,
      "conversion_attempts": 2,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 16,
      "final_total_tokens": 6866,
      "final_warnings": "CROSS APPLY/STRING_SPLIT rewritten using FIND_IN_SET; consider normalization for scale."
    },
    {
      "script_id": 57,
      "script_file": "0057_quick_look_customers_rows.sql",
      "title": "Quick look: Customers rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Customers",
      "executions": 14,
      "total_duration_ms": 641,
      "avg_duration_ms": 45.79,
      "total_cpu_ms": 412,
      "total_reads": 10564,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 10,
      "final_total_tokens": 5125,
      "final_warnings": null
    },
    {
      "script_id": 58,
      "script_file": "0058_quick_look_products_rows.sql",
      "title": "Quick look: Products rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Products",
      "executions": 162,
      "total_duration_ms": 19932,
      "avg_duration_ms": 123.04,
      "total_cpu_ms": 13548,
      "total_reads": 339940,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 10,
      "final_total_tokens": 4967,
      "final_warnings": null
    },
    {
      "script_id": 59,
      "script_file": "0059_top_customers_by_revenue_last_90_days.sql",
      "title": "Top customers by revenue (last 90 days)",
      "category": "query",
      "complexity": 5,
      "needs_manual_review": false,
      "tags": "SELECT|join|aggregate|CTE|WINDOW|TOP|DATEADD",
      "tables": "Customers|Orders",
      "executions": 6,
      "total_duration_ms": 1821,
      "avg_duration_ms": 303.5,
      "total_cpu_ms": 1373,
      "total_reads": 32441,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 18,
      "final_total_tokens": 4536,
      "final_warnings": null
    },
    {
      "script_id": 60,
      "script_file": "0060_quick_look_products_rows.sql",
      "title": "Quick look: Products rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Products",
      "executions": 7,
      "total_duration_ms": 1197,
      "avg_duration_ms": 171.0,
      "total_cpu_ms": 744,
      "total_reads": 20537,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 25,
      "final_total_tokens": 6195,
      "final_warnings": null
    },
    {
      "script_id": 61,
      "script_file": "0061_quick_look_pageviews_rows.sql",
      "title": "Quick look: PageViews rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "PageViews",
      "executions": 51,
      "total_duration_ms": 6256,
      "avg_duration_ms": 122.67,
      "total_cpu_ms": 4352,
      "total_reads": 106211,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 22,
      "final_total_tokens": 4783,
      "final_warnings": null
    },
    {
      "script_id": 62,
      "script_file": "0062_store_sales_by_category_last_7_days.sql",
      "title": "Store sales by category (last 7 days)",
      "category": "report",
      "complexity": 6,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 5,
      "total_duration_ms": 2224,
      "avg_duration_ms": 444.8,
      "total_cpu_ms": 1427,
      "total_reads": 37122,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 29,
      "final_total_tokens": 5510,
      "final_warnings": null
    },
    {
      "script_id": 63,
      "script_file": "0063_quick_look_products_rows.sql",
      "title": "Quick look: Products rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Products",
      "executions": 5,
      "total_duration_ms": 60,
      "avg_duration_ms": 12.0,
      "total_cpu_ms": 42,
      "total_reads": 1125,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 25,
      "final_total_tokens": 3002,
      "final_warnings": null
    },
    {
      "script_id": 64,
      "script_file": "0064_quick_look_pageviews_rows.sql",
      "title": "Quick look: PageViews rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "PageViews",
      "executions": 17,
      "total_duration_ms": 882,
      "avg_duration_ms": 51.88,
      "total_cpu_ms": 638,
      "total_reads": 13758,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 16,
      "final_total_tokens": 6303,
      "final_warnings": null
    },
    {
      "script_id": 65,
      "script_file": "0065_quick_look_customers_rows.sql",
      "title": "Quick look: Customers rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "Customers",
      "executions": 29,
      "total_duration_ms": 1649,
      "avg_duration_ms": 56.86,
      "total_cpu_ms": 1153,
      "total_reads": 27765,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 17,
      "final_total_tokens": 5613,
      "final_warnings": null
    },
    {
      "script_id": 66,
      "script_file": "0066_stored_procedure_capture_payment_update_order_status.sql",
      "title": "Stored procedure: capture payment + update order status",
      "category": "procedure",
      "complexity": 9,
      "needs_manual_review": true,
      "tags": "PROC|TRY/CATCH|TRANSACTION",
      "tables": "Orders|Payments",
      "executions": 19,
      "total_duration_ms": 20145,
      "avg_duration_ms": 1060.26,
      "total_cpu_ms": 11835,
      "total_reads": 359902,
      "conversion_attempts": 2,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 33,
      "final_total_tokens": 4765,
      "final_warnings": "TRY/CATCH -> handler blocks; session context differs; @app_user is demo placeholder."
    },
    {
      "script_id": 67,
      "script_file": "0067_store_sales_by_category_last_90_days.sql",
      "title": "Store sales by category (last 90 days)",
      "category": "report",
      "complexity": 7,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 26,
      "total_duration_ms": 30993,
      "avg_duration_ms": 1192.04,
      "total_cpu_ms": 21094,
      "total_reads": 492039,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 16,
      "final_total_tokens": 5970,
      "final_warnings": null
    },
    {
      "script_id": 68,
      "script_file": "0068_quick_look_products_rows.sql",
      "title": "Quick look: Products rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Products",
      "executions": 17,
      "total_duration_ms": 2105,
      "avg_duration_ms": 123.82,
      "total_cpu_ms": 1433,
      "total_reads": 36076,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 13,
      "final_total_tokens": 3083,
      "final_warnings": null
    },
    {
      "script_id": 69,
      "script_file": "0069_quick_look_payments_rows.sql",
      "title": "Quick look: Payments rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Payments",
      "executions": 10,
      "total_duration_ms": 511,
      "avg_duration_ms": 51.1,
      "total_cpu_ms": 377,
      "total_reads": 8195,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 20,
      "final_total_tokens": 4849,
      "final_warnings": null
    },
    {
      "script_id": 70,
      "script_file": "0070_quick_look_products_rows.sql",
      "title": "Quick look: Products rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Products",
      "executions": 9,
      "total_duration_ms": 518,
      "avg_duration_ms": 57.56,
      "total_cpu_ms": 376,
      "total_reads": 8275,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 12,
      "final_total_tokens": 5082,
      "final_warnings": null
    },
    {
      "script_id": 71,
      "script_file": "0071_quick_look_customers_rows.sql",
      "title": "Quick look: Customers rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Customers",
      "executions": 19,
      "total_duration_ms": 233,
      "avg_duration_ms": 12.26,
      "total_cpu_ms": 148,
      "total_reads": 4082,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 14,
      "final_total_tokens": 3593,
      "final_warnings": null
    },
    {
      "script_id": 72,
      "script_file": "0072_quick_look_orders_rows.sql",
      "title": "Quick look: Orders rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD|IN",
      "tables": "Orders",
      "executions": 222,
      "total_duration_ms": 12121,
      "avg_duration_ms": 54.6,
      "total_cpu_ms": 8032,
      "total_reads": 206530,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 21,
      "final_total_tokens": 4605,
      "final_warnings": null
    },
    {
      "script_id": 73,
      "script_file": "0073_monthly_revenue_pivot_by_store.sql",
      "title": "Monthly revenue pivot by store",
      "category": "report",
      "complexity": 8,
      "needs_manual_review": true,
      "tags": "PIVOT|reporting",
      "tables": "Orders|Stores",
      "executions": 13,
      "total_duration_ms": 14271,
      "avg_duration_ms": 1097.77,
      "total_cpu_ms": 9267,
      "total_reads": 240895,
      "conversion_attempts": 2,
      "final_status": "passed_with_notes",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 20,
      "final_total_tokens": 4866,
      "final_warnings": "PIVOT rewritten as conditional aggregation; verify performance & indexes."
    },
    {
      "script_id": 74,
      "script_file": "0074_view_customer_promo_codes_seen_string_agg.sql",
      "title": "View: customer promo codes seen (STRING_AGG)",
      "category": "view",
      "complexity": 7,
      "needs_manual_review": true,
      "tags": "VIEW|STRING_AGG|reporting",
      "tables": "Customers|Promotions",
      "executions": 4,
      "total_duration_ms": 1553,
      "avg_duration_ms": 388.25,
      "total_cpu_ms": 990,
      "total_reads": 25970,
      "conversion_attempts": 2,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 45,
      "final_total_tokens": 6727,
      "final_warnings": "STRING_AGG -> GROUP_CONCAT; check max length (group_concat_max_len)."
    },
    {
      "script_id": 75,
      "script_file": "0075_quick_look_payments_rows.sql",
      "title": "Quick look: Payments rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Payments",
      "executions": 7,
      "total_duration_ms": 86,
      "avg_duration_ms": 12.29,
      "total_cpu_ms": 62,
      "total_reads": 1424,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 11,
      "final_total_tokens": 3944,
      "final_warnings": null
    },
    {
      "script_id": 76,
      "script_file": "0076_upsert_inventory_movements_from_staging_merge.sql",
      "title": "Upsert inventory movements from staging (MERGE)",
      "category": "etl",
      "complexity": 8,
      "needs_manual_review": true,
      "tags": "MERGE|ETL|upsert",
      "tables": "InventoryMovements",
      "executions": 38,
      "total_duration_ms": 74642,
      "avg_duration_ms": 1964.26,
      "total_cpu_ms": 49968,
      "total_reads": 1259746,
      "conversion_attempts": 2,
      "final_status": "passed_with_notes",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 29,
      "final_total_tokens": 6957,
      "final_warnings": "MERGE requires redesign in MySQL (unique key + upsert)."
    },
    {
      "script_id": 77,
      "script_file": "0077_store_sales_by_category_last_90_days.sql",
      "title": "Store sales by category (last 90 days)",
      "category": "report",
      "complexity": 4,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 12,
      "total_duration_ms": 3299,
      "avg_duration_ms": 274.92,
      "total_cpu_ms": 2323,
      "total_reads": 52578,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 19,
      "final_total_tokens": 5692,
      "final_warnings": null
    },
    {
      "script_id": 78,
      "script_file": "0078_ad_hoc_troubleshooting_query_nolock.sql",
      "title": "Ad-hoc troubleshooting query (NOLOCK)",
      "category": "query",
      "complexity": 6,
      "needs_manual_review": true,
      "tags": "NOLOCK|performance|TOP",
      "tables": "Orders",
      "executions": 12,
      "total_duration_ms": 3882,
      "avg_duration_ms": 323.5,
      "total_cpu_ms": 2646,
      "total_reads": 66022,
      "conversion_attempts": 3,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 18,
      "final_total_tokens": 5066,
      "final_warnings": "Removed NOLOCK hint; consider transaction isolation needs"
    },
    {
      "script_id": 79,
      "script_file": "0079_monthly_revenue_pivot_by_store.sql",
      "title": "Monthly revenue pivot by store",
      "category": "report",
      "complexity": 8,
      "needs_manual_review": true,
      "tags": "PIVOT|reporting",
      "tables": "Orders|Stores",
      "executions": 30,
      "total_duration_ms": 36203,
      "avg_duration_ms": 1206.77,
      "total_cpu_ms": 24237,
      "total_reads": 543075,
      "conversion_attempts": 2,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 24,
      "final_total_tokens": 6679,
      "final_warnings": "PIVOT rewritten as conditional aggregation; verify performance & indexes."
    },
    {
      "script_id": 80,
      "script_file": "0080_ingest_order_items_from_json_payload_openjson.sql",
      "title": "Ingest order items from JSON payload (OPENJSON)",
      "category": "etl",
      "complexity": 9,
      "needs_manual_review": true,
      "tags": "OPENJSON|JSON|ETL",
      "tables": "OrderItems",
      "executions": 33,
      "total_duration_ms": 86959,
      "avg_duration_ms": 2635.12,
      "total_cpu_ms": 58838,
      "total_reads": 1424190,
      "conversion_attempts": 2,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 18,
      "final_total_tokens": 5764,
      "final_warnings": "OPENJSON -> JSON_TABLE (MySQL 8). Confirm JSON types and precision."
    },
    {
      "script_id": 81,
      "script_file": "0081_ingest_order_items_from_json_payload_openjson.sql",
      "title": "Ingest order items from JSON payload (OPENJSON)",
      "category": "etl",
      "complexity": 9,
      "needs_manual_review": true,
      "tags": "OPENJSON|JSON|ETL",
      "tables": "OrderItems",
      "executions": 25,
      "total_duration_ms": 50311,
      "avg_duration_ms": 2012.44,
      "total_cpu_ms": 33079,
      "total_reads": 829791,
      "conversion_attempts": 3,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 30,
      "final_total_tokens": 7150,
      "final_warnings": "OPENJSON -> JSON_TABLE (MySQL 8). Confirm JSON types and precision."
    },
    {
      "script_id": 82,
      "script_file": "0082_ad_hoc_troubleshooting_query_nolock.sql",
      "title": "Ad-hoc troubleshooting query (NOLOCK)",
      "category": "query",
      "complexity": 6,
      "needs_manual_review": true,
      "tags": "NOLOCK|performance|TOP",
      "tables": "Orders",
      "executions": 15,
      "total_duration_ms": 6635,
      "avg_duration_ms": 442.33,
      "total_cpu_ms": 5258,
      "total_reads": 99197,
      "conversion_attempts": 3,
      "final_status": "failed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 19,
      "final_total_tokens": 5549,
      "final_warnings": "Removed NOLOCK hint; consider transaction isolation needs"
    },
    {
      "script_id": 83,
      "script_file": "0083_quick_look_orders_rows.sql",
      "title": "Quick look: Orders rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD|IN",
      "tables": "Orders",
      "executions": 45,
      "total_duration_ms": 5501,
      "avg_duration_ms": 122.24,
      "total_cpu_ms": 3642,
      "total_reads": 88752,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 23,
      "final_total_tokens": 5365,
      "final_warnings": null
    },
    {
      "script_id": 84,
      "script_file": "0084_store_sales_by_category_last_60_days.sql",
      "title": "Store sales by category (last 60 days)",
      "category": "report",
      "complexity": 6,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 13,
      "total_duration_ms": 7798,
      "avg_duration_ms": 599.85,
      "total_cpu_ms": 5728,
      "total_reads": 136811,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 20,
      "final_total_tokens": 4790,
      "final_warnings": null
    },
    {
      "script_id": 85,
      "script_file": "0085_quick_look_inventorymovements_rows.sql",
      "title": "Quick look: InventoryMovements rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "InventoryMovements",
      "executions": 44,
      "total_duration_ms": 2145,
      "avg_duration_ms": 48.75,
      "total_cpu_ms": 1400,
      "total_reads": 35916,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 11,
      "final_total_tokens": 5660,
      "final_warnings": null
    },
    {
      "script_id": 86,
      "script_file": "0086_store_sales_by_category_last_30_days.sql",
      "title": "Store sales by category (last 30 days)",
      "category": "report",
      "complexity": 4,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 32,
      "total_duration_ms": 8697,
      "avg_duration_ms": 271.78,
      "total_cpu_ms": 5895,
      "total_reads": 140600,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 29,
      "final_total_tokens": 6319,
      "final_warnings": null
    },
    {
      "script_id": 87,
      "script_file": "0087_quick_look_payments_rows.sql",
      "title": "Quick look: Payments rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Payments",
      "executions": 13,
      "total_duration_ms": 1294,
      "avg_duration_ms": 99.54,
      "total_cpu_ms": 789,
      "total_reads": 21635,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 14,
      "final_total_tokens": 5041,
      "final_warnings": null
    },
    {
      "script_id": 88,
      "script_file": "0088_quick_look_pageviews_rows.sql",
      "title": "Quick look: PageViews rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "PageViews",
      "executions": 9,
      "total_duration_ms": 115,
      "avg_duration_ms": 12.78,
      "total_cpu_ms": 63,
      "total_reads": 1837,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 9,
      "final_total_tokens": 4180,
      "final_warnings": null
    },
    {
      "script_id": 89,
      "script_file": "0089_ad_hoc_troubleshooting_query_nolock.sql",
      "title": "Ad-hoc troubleshooting query (NOLOCK)",
      "category": "query",
      "complexity": 6,
      "needs_manual_review": true,
      "tags": "NOLOCK|performance|TOP",
      "tables": "Orders",
      "executions": 23,
      "total_duration_ms": 10407,
      "avg_duration_ms": 452.48,
      "total_cpu_ms": 7072,
      "total_reads": 192049,
      "conversion_attempts": 3,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 20,
      "final_total_tokens": 5115,
      "final_warnings": "Removed NOLOCK hint; consider transaction isolation needs"
    },
    {
      "script_id": 90,
      "script_file": "0090_quick_look_products_rows.sql",
      "title": "Quick look: Products rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP",
      "tables": "Products",
      "executions": 36,
      "total_duration_ms": 4345,
      "avg_duration_ms": 120.69,
      "total_cpu_ms": 2748,
      "total_reads": 76594,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 14,
      "final_total_tokens": 5349,
      "final_warnings": null
    },
    {
      "script_id": 91,
      "script_file": "0091_backfill_orderitems_linetotal_and_orders_total.sql",
      "title": "Backfill OrderItems.LineTotal and Orders.Total",
      "category": "maintenance",
      "complexity": 4,
      "needs_manual_review": true,
      "tags": "DML|maintenance|TRANSACTION",
      "tables": "OrderItems|Orders",
      "executions": 5,
      "total_duration_ms": 2046,
      "avg_duration_ms": 409.2,
      "total_cpu_ms": 1434,
      "total_reads": 35558,
      "conversion_attempts": 3,
      "final_status": "failed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 27,
      "final_total_tokens": 4542,
      "final_warnings": "UPDATE ... FROM rewritten using JOIN; validate totals and rounding behavior."
    },
    {
      "script_id": 92,
      "script_file": "0092_store_sales_by_category_last_180_days.sql",
      "title": "Store sales by category (last 180 days)",
      "category": "report",
      "complexity": 7,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 24,
      "total_duration_ms": 23715,
      "avg_duration_ms": 988.13,
      "total_cpu_ms": 15792,
      "total_reads": 404492,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 30,
      "final_total_tokens": 5829,
      "final_warnings": null
    },
    {
      "script_id": 93,
      "script_file": "0093_quick_look_pageviews_rows.sql",
      "title": "Quick look: PageViews rows",
      "category": "query",
      "complexity": 1,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "PageViews",
      "executions": 8,
      "total_duration_ms": 105,
      "avg_duration_ms": 13.13,
      "total_cpu_ms": 62,
      "total_reads": 1727,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 11,
      "final_total_tokens": 4588,
      "final_warnings": null
    },
    {
      "script_id": 94,
      "script_file": "0094_quick_look_pageviews_rows.sql",
      "title": "Quick look: PageViews rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "PageViews",
      "executions": 15,
      "total_duration_ms": 1486,
      "avg_duration_ms": 99.07,
      "total_cpu_ms": 949,
      "total_reads": 25588,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 15,
      "final_total_tokens": 5398,
      "final_warnings": null
    },
    {
      "script_id": 95,
      "script_file": "0095_store_sales_by_category_last_60_days.sql",
      "title": "Store sales by category (last 60 days)",
      "category": "report",
      "complexity": 6,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 5,
      "total_duration_ms": 3695,
      "avg_duration_ms": 739.0,
      "total_cpu_ms": 2510,
      "total_reads": 64859,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 13,
      "final_total_tokens": 3500,
      "final_warnings": null
    },
    {
      "script_id": 96,
      "script_file": "0096_top_customers_by_revenue_last_90_days.sql",
      "title": "Top customers by revenue (last 90 days)",
      "category": "query",
      "complexity": 6,
      "needs_manual_review": false,
      "tags": "SELECT|join|aggregate|CTE|WINDOW|TOP|DATEADD",
      "tables": "Customers|Orders",
      "executions": 9,
      "total_duration_ms": 4475,
      "avg_duration_ms": 497.22,
      "total_cpu_ms": 2992,
      "total_reads": 80544,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1",
      "final_elapsed_seconds": 20,
      "final_total_tokens": 5748,
      "final_warnings": null
    },
    {
      "script_id": 97,
      "script_file": "0097_store_sales_by_category_last_180_days.sql",
      "title": "Store sales by category (last 180 days)",
      "category": "report",
      "complexity": 5,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 10,
      "total_duration_ms": 4793,
      "avg_duration_ms": 479.3,
      "total_cpu_ms": 2922,
      "total_reads": 90272,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-4.1-mini",
      "final_elapsed_seconds": 19,
      "final_total_tokens": 4614,
      "final_warnings": null
    },
    {
      "script_id": 98,
      "script_file": "0098_store_sales_by_category_last_14_days.sql",
      "title": "Store sales by category (last 14 days)",
      "category": "report",
      "complexity": 6,
      "needs_manual_review": false,
      "tags": "SELECT|join|groupby|TOP|DATEADD",
      "tables": "Categories|OrderItems|Orders|Products|Stores",
      "executions": 18,
      "total_duration_ms": 12303,
      "avg_duration_ms": 683.5,
      "total_cpu_ms": 8298,
      "total_reads": 192926,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "claude-3.5-sonnet",
      "final_elapsed_seconds": 17,
      "final_total_tokens": 5232,
      "final_warnings": null
    },
    {
      "script_id": 99,
      "script_file": "0099_quick_look_inventorymovements_rows.sql",
      "title": "Quick look: InventoryMovements rows",
      "category": "query",
      "complexity": 2,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD",
      "tables": "InventoryMovements",
      "executions": 6,
      "total_duration_ms": 273,
      "avg_duration_ms": 45.5,
      "total_cpu_ms": 206,
      "total_reads": 3668,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gemini-2.5-pro",
      "final_elapsed_seconds": 8,
      "final_total_tokens": 3812,
      "final_warnings": null
    },
    {
      "script_id": 100,
      "script_file": "0100_quick_look_orders_rows.sql",
      "title": "Quick look: Orders rows",
      "category": "query",
      "complexity": 3,
      "needs_manual_review": false,
      "tags": "SELECT|simple|TOP|DATEADD|IN",
      "tables": "Orders",
      "executions": 51,
      "total_duration_ms": 6464,
      "avg_duration_ms": 126.75,
      "total_cpu_ms": 4409,
      "total_reads": 100320,
      "conversion_attempts": 1,
      "final_status": "passed",
      "final_model": "gpt-5.2-thinking",
      "final_elapsed_seconds": 16,
      "final_total_tokens": 3911,
      "final_warnings": null
    }
  ]
}
;
